services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-net
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "3",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka1:
    image: apache/kafka:3.7.0
    container_name: kafka1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,EXTERNAL://localhost:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9094,2@kafka2:9094,3@kafka3:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - iot-net
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-topics.sh",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  kafka2:
    image: apache/kafka:3.7.0
    container_name: kafka2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9095,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,EXTERNAL://localhost:9095
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9094,2@kafka2:9094,3@kafka3:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    ports:
      - "9095:9095"
    networks:
      - iot-net
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-topics.sh",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  kafka3:
    image: apache/kafka:3.7.0
    container_name: kafka3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9096,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,EXTERNAL://localhost:9096
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9094,2@kafka2:9094,3@kafka3:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    ports:
      - "9096:9096"
    networks:
      - iot-net
    healthcheck:
      test:
        [
          "CMD",
          "/opt/kafka/bin/kafka-topics.sh",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot123
      POSTGRES_DB: iotdb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - iot-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot -d iotdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion:
    build: ./ingestion
    container_name: ingestion
    depends_on:
      mosquitto:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    environment:
      MQTT_BROKER: mqtt://mosquitto:1883
      KAFKA_BROKER: kafka1:9092,kafka2:9092,kafka3:9092
      NUM_DEVICES: "10"
      INTERVAL_MS: "100"
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
    networks:
      - iot-net
    restart: on-failure

  storage:
    build: ./storage
    #container_name: storage
    depends_on:
      mosquitto:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      MQTT_BROKER: mosquitto
      KAFKA_BROKER: kafka1:9092,kafka2:9092,kafka3:9092
      DATABASE_URL: postgresql://iot:iot123@postgres:5432/iotdb
    networks:
      - iot-net
    restart: on-failure

  analytics:
    build: ./analytics
    container_name: analytics
    depends_on:
      mosquitto:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    environment:
      MQTT_BROKER: mqtt://mosquitto:1883
      KAFKA_BROKER: kafka1:9092,kafka2:9092,kafka3:9092
      ALERT_THRESHOLD: "35"
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
    networks:
      - iot-net
    restart: on-failure

volumes:
  postgres-data:

networks:
  iot-net:
    driver: bridge
